### ISSUE TITLE
Nice codebase

### ISSUE THREAD

**Issue by p0psicles** [rubenvereecken/pokemongo-api#1]
Will be watching this! Like your OO approach.  Your accepting PR's? On IRC?

**Comment by rubenvereecken** [comment]
I should get a communication channel, not sure where though. Might go on Slack/Gitter.

Don't have incredible amounts of time to spend this though. Investigating the proto's that go over the wire is slow-going especially, so I'll probably look out what others can make of it and incorporate into this API. So yes, definitely accepting PRs.

**Comment by dmadisetti** [comment]
@rubenvereecken 
Slack channel https://pkre.slack.com/messages/reversing/
and a more organized proto repo https://github.com/AeonLucid/POGOProtos

**Comment by rubenvereecken** [comment]
Looks like I'll visit that channel then. Drop me a line there @p0psicles whenever you want.

**Comment by m3talstorm** [comment]
Please follow standard Python naming conventions and format.

**Comment by rubenvereecken** [comment]
@m3talstorm this started out as a Py 3.5 project but I switched because the generated code was crap. But you're right, it's an issue.
