### ISSUE TITLE
Question about use

### ISSUE THREAD

**Issue by jagauthier** [rubenvereecken/pokemongo-api#101]
Sorry, this isn't an issue!  I've read through the code a little, and I'm trying to determine if I can obtain two pieces of information.

1) Pokemon inventory data.
Can I get their CP, HP, moves, etc?

2) Egg data
Can I obtain the egg distances?

I'm interested in doing analysis on my pokemon as they are in my inventory.  I'm not completely aware of the TOS, but would not use this for scanning, catching, or other activities. Simply accessing the data.  Will that still put me at risk? (probably)

**Comment by dnsBlah** [comment]
check the inventory
contains all data you are requesting

**Comment by dmadisetti** [comment]
@jagauthier If you run with location == None you'll be least likely to have problems.

There's sensor data this api pretty much just ignores which Niantic uses for determining 3rd party usage- but as long as your load it light, you should be fine

**Comment by jagauthier** [comment]
Thanks!  I appreciate that!
