### ISSUE TITLE
AttributeError: 'str' object has no attribute 'noop'

### ISSUE THREAD

**Issue by retep-mathwizard** [rubenvereecken/pokemongo-api#106]
My code:
```
location ="35.493149, -80.832093"
mysession = PogoSession(PogoSessionBare(session, location))
mysession.getEggs()
```
Error:
```
  File "./walkbot", line 71, in <module>
    mysession = PogoSession(PogoSessionBare(thesession, location))
  File "/usr/local/lib/python2.7/site-packages/pogo/session_bare.py", line 74, in __init__
    if self._location.noop:
AttributeError: 'str' object has no attribute 'noop'
```

**Comment by dmadisetti** [comment]
No that's right. Session bare isn't supposed to be instantiated like that.

    # Create PokoAuthObject
    auth_session = PokeAuthSession(
        "user",
        "pass",
        "ptc",
        "thing.so",
        geo_key=key,
    )
   location ="35.493149, -80.832093"
   mysession = auth_session.authenticate(locationLookup=location)

**Comment by retep-mathwizard** [comment]
How do I use `getEggs`?

**Comment by dmadisetti** [comment]
mysession.getProfile()
    mysession.inventroy.eggs
