### ISSUE TITLE
Bug in findClosestPokemon in demo.py

### ISSUE THREAD

**Issue by mcteo** [rubenvereecken/pokemongo-api#15]
I think there is a small bug in demo.py `findClosestPokemon`. If dist < closest, you update pokemonBest, but not closest, which means pokemonBest will be the last pokemon in the list, rather than the nearest.

**Comment by mcteo** [comment]
https://github.com/rubenvereecken/pokemongo-api/pull/16 fixes this issue

**Comment by mcteo** [comment]
Pull Request #16 fixes this issue.

**Comment by dmadisetti** [comment]
Merged
