### ISSUE TITLE
[refactoring] change check... methods to properties

### ISSUE THREAD

**Issue by paledrewnem** [rubenvereecken/pokemongo-api#20]
As above. Methods from class Session have checks that only returns local cached response. Name `check` indicates for checking, not returning something.

Can we change it to properties? It might look like this 

`
session.eggs

session.inventory

session.badges

session.download_settings
`

**Comment by dmadisetti** [comment]
Direct access is possible with session.state.eggs. We could, but state is ideally private. Now you mention it, I'll probably change `state` to `_state`

**Comment by dmadisetti** [comment]
Actually, wanted to point out you're right. Was unfamiliar with property decorator
