### ISSUE TITLE
Malformed response

### ISSUE THREAD

**Issue by poingg** [rubenvereecken/pokemongo-api#22]
Something must have changed in the API as today this started to happen only when trying to catch a pokemon. Everything else seems to be ok.

<pre><code>
Line 80,demo.py - 2016-07-24 10:33:25,047 - INFO - Catching RHYHORN:
Line 473,session.py - 2016-07-24 10:33:25,047 - INFO - Walking 25.147343 meters. This will take 7.858545 seconds...
Line 193,session.py - 2016-07-24 10:33:34,880 - ERROR - list index out of range
Traceback (most recent call last):
  File "demo.py", line 251, in <module>
    walkAndCatch(session, pokemon)
  File "demo.py", line 82, in walkAndCatch
    logging.info(session.encounterAndCatch(pokemon))
  File "/Users/eep/Work/Pokemon/pokemongo-api/pogo/session.py", line 496, in encounterAndCatch
    return self.catchPokemon(pokemon, pokeball)
  File "/Users/eep/Work/Pokemon/pokemongo-api/pogo/session.py", line 362, in catchPokemon
    res = self.wrapAndRequest(payload)
  File "/Users/eep/Work/Pokemon/pokemongo-api/pogo/session.py", line 144, in wrapAndRequest
    self.parseDefault(res)
  File "/Users/eep/Work/Pokemon/pokemongo-api/pogo/session.py", line 194, in parseDefault
    raise GeneralPogoException("Error parsing response. Malformed response")
custom_exceptions.GeneralPogoException: Error parsing response. Malformed response
</code></pre>

**Comment by poingg** [comment]
A bit more debugging and it looks like returns is empty?
status_code: 3
request_id: 138837240061
returns: ""

**Comment by poingg** [comment]
<pre><code>
Line 80,demo.py - 2016-07-24 11:20:19,010 - INFO - Catching ELECTABUZZ:
Line 474,session.py - 2016-07-24 11:20:19,010 - INFO - Walking 83.982241 meters. This will take 26.244450 seconds...
Traceback (most recent call last):
  File "demo.py", line 251, in <module>
    walkAndCatch(session, pokemon)
  File "demo.py", line 82, in walkAndCatch
    logging.info(session.encounterAndCatch(pokemon))
  File "/Users/eep/Work/Pokemon/pokemongo-api/pogo/session.py", line 497, in encounterAndCatch
    return self.catchPokemon(pokemon, pokeball)
  File "/Users/eep/Work/Pokemon/pokemongo-api/pogo/session.py", line 358, in catchPokemon
    normalized_hit_position=1.0
  File "/Users/eep/env/pokemon/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 496, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/Users/eep/env/pokemon/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 560, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message CatchPokemonMessage has no "spawn_point_guid" field.
</pre>
</code>

**Comment by rubenvereecken** [comment]
I'm really not sure where you get that last error from. It definitely has the field: https://github.com/AeonLucid/POGOProtos/blob/eeccbb121b126aa51fc4eebae8d2f23d013e1cb8/src/POGOProtos/Networking/Requests/Messages/CatchPokemonMessage.proto

**Comment by rubenvereecken** [comment]
Alright enlighten us, what just happened?

**Comment by poingg** [comment]
Something odd. Let's see... Installed 3.0.0-beta3, ran it again and the walkandcatch seems to be working again.

That error msg came up when I compiled the .proto files to python and ran with that.

**Comment by poingg** [comment]
So basically I am now running with a newly compiled protobuf instead of the pip version from requirements though it seems to be the same version.
The really odd thing here is that last night it was running smooth. Problems started this morning without any code changes.

**Comment by poingg** [comment]
I would say it has something to do with unstable servers as I keep getting this every once in a while
Line 194,session.py - 2016-07-24 11:37:14,429 - ERROR - list index out of range
Line 198,demo.py - 2016-07-24 11:37:14,429 - CRITICAL - GeneralPogoException raised: Error parsing response. Malformed response

Again with empty reponses

**Comment by poingg** [comment]
And it's back... I would say one needs to handle that exception

status_code: 3
request_id: 613580500550
returns: ""

Line 194,session.py - 2016-07-24 12:02:51,268 - ERROR - list index out of range
Line 198,demo.py - 2016-07-24 12:02:51,269 - CRITICAL - GeneralPogoException raised: Error parsing response. Malformed response

**Comment by p0psicles** [comment]
Yeah.  U just catch it in the demo.py.  Or whatever you start as Main. And do the authenticate(). The reauthenticate isn't working well.

**Comment by poingg** [comment]
Looks like Niantic is doing something about this. I stopped the script and ran the app on my phone. Every catch I tried failed. After launching the ball the pokemon flees immediately.

**Comment by dmadisetti** [comment]
So CATCH_FLEE is indicative of been softbanned. It only lasts for like and hour. Dw, It's happened to me a ton

**Comment by p0psicles** [comment]
You can keep catching pokemons or visit stops, as long as it's approx within a radius of 15 km. So when you'r living in new york, and you've set it to search in boston. That's fine. But then you shouldn't login on your phone. So if you set it to start searching in new york, within a radius of 15 km, your good.
