### ISSUE TITLE
Needs Python packaging 

### ISSUE THREAD

**Issue by douglascamata** [rubenvereecken/pokemongo-api#23]
I want so bad to be able to `pip install pogo`.

**Comment by IamCarbonMan** [comment]
+1. I'm writing a bot that could really benefit from this.

**Comment by rubenvereecken** [comment]
Wip

**Comment by TechnicalBro** [comment]
After working on this for quite some time, Its ready! I created a pull request and inside is a version of the API ready to be packaged and sent to pypi! 

Further work will come, when versioning is solidified and so forth.
