### ISSUE TITLE
Exception 17 during mass evolve

### ISSUE THREAD

**Issue by dnsBlah** [rubenvereecken/pokemongo-api#41]
I rewrote a little part of the evolveAll function

```
def evolveAllPokemon(session):
    for pokemon in curInventory.party:
        currentID = pokemon.pokemon_id
        currentPokemon = pokedex[currentID]

        candies = session.checkInventory().candies[currentID]
        requiredCandies = pokedex.evolves[currentID]

        if requiredCandies > 0:
            if candies > requiredCandies:
                evolveResult = session.evolvePokemon(pokemon)
                time.sleep(1.5)
                if evolveResult.result == 1:
                    print("Evolved...")
        time.sleep(1)
```

I already found out, that when I started using defined vars currentID, currentPokemon, requiredCandies, that the loop will last longer.
The sleep function did not make any difference

I can go up till 6, and then I get the exception.

Anyone has any idea why? And how to solve it?
It doesn't seem to be such a big deal tho.

Is it something with CPU? RAM?

I do find the process really intensive, as my macbook's fans are running on max speed and cpu is still reaching 80 degrees Celcius :-D

**Comment by kwkroll32** [comment]
I haven't tried this yet but will be keeping an eye on it. I have several dozen evolutions saved up, and it'd be way easier via the api, instead of manually using the app. 

I doubt that your local hardware is a limitation. Keep in mind that these functions (or at least similar fxns) run on mobile phones. Your laptop should have more than enough CPU/RAM by comparison.

**Comment by dnsBlah** [comment]
Im guessing its an request throttle
should call the candies once
get each single pokemon_id
calculate the times I can evolve it
and loop through that list

i did evolve like 120 rattata's in seconds tho ;P
