### ISSUE TITLE
First time login

### ISSUE THREAD

**Issue by bolds07** [rubenvereecken/pokemongo-api#45]
Are there any way to deal with the first login settings programatically?
I mean, select skin color, clothes, name, and check that first agreement

If I create a new account, the bot doesn't see any pokestop or catchable pokemon until I go manually throught this first settings

Probably this is not on the roadmap of the API if someone can give me a tip about how to decript the packages and figure by myself the protocol I would be very glad

**Comment by dmadisetti** [comment]
If you want to implement this in yourself, feel free- but I have no plans of doing this myself.

You'll need to reference these protos https://github.com/AeonLucid/POGOProtos

Just folow the format in `session.py`. If you submit a pull request I will merge it in though.
