### ISSUE TITLE
No Check for Full Pokemon Inventory

### ISSUE THREAD

**Issue by kwkroll32** [rubenvereecken/pokemongo-api#57]
It seems like there is no check for whether a trainer is at their max number of pokemon. I encountered this problem, and trainer.encounterAndCatch was unable to determine a "bestBall" or "altBall." The encounter itself clearly states that the trainer's pokemon list is full, but the program throws the, "out of usable balls," exception.

**Comment by dnsBlah** [comment]
I always do this check before I even do findnearpokemon

**Comment by dnsBlah** [comment]
```
if (len(session.inventory.party) + len(session.inventory.eggs)) < session.getProfile().player_data.max_pokemon_storage:
# Go search and catch pokemons
```

**Comment by dmadisetti** [comment]
Implemented https://github.com/rubenvereecken/pokemongo-api/blob/master/pogo/demo.py#L94
