### ISSUE TITLE
Reduce frequency of GetMapObjects calls

### ISSUE THREAD

**Issue by hwaterke** [rubenvereecken/pokemongo-api#64]
Aren't we suppose to wait 5 seconds now (with the new changes) between two GetMapObjects calls?
Ideally the bot would use the values sent by the server to cope with further changes in that regard.

```
Line 525,session.py - 2016-08-02 08:14:51,945 - INFO - Walking 316.470710 meters. This will take 98.897097 seconds...
Line 147,session.py - 2016-08-02 08:15:14,238 - ERROR - ('Connection aborted.', error(104, 'Connection reset by peer'))
Line 443,demo.py - 2016-08-02 08:15:14,243 - CRITICAL - GeneralPogoException raised: Probably server fires.
```

**Comment by rubenvereecken** [comment]
Yep, you're right. Things have been changing. Don't have the time to patch this in though. If you ever feel so inclined, feel free to submit us a PR!

**Comment by dmadisetti** [comment]
It's pretty slow now

**Comment by dnsBlah** [comment]
just get the forts first and save them to loop through
when waked like 5-10 steps do a check for pokemon
and when arrived
