### ISSUE TITLE
errors while using items

### ISSUE THREAD

**Issue by dnsBlah** [rubenvereecken/pokemongo-api#65]
For using Raspberries or Catching pokemons I'm finding a lot of issues
responses with status_code 3 etc
even with a delay of 10 seconds, i still get this status_code

**Comment by rubenvereecken** [comment]
I'm actually not sure what 3 is supposed to mean?

**Comment by dnsBlah** [comment]
3 should be an ... bad request or whatever.
But I'm now also getting it on get_map_objects, everywhere

then I receive it, and then I dont :-/
loads of cooldown timers

```
(in the session request)
If response != 1
   return None

(in the bot)
if getForts == None
    cooldown = 0
    while getForts == None
        time.sleep(5+cooldown)
        getForts = session.getForts()
        if cooldown == 5: break
        cooldown += 1
    if getForts == None:
        print("No forts")
        return None
```

Something sketchy like that

**Comment by dnsBlah** [comment]
issue does not occure anymore since update
