### ISSUE TITLE
Update the API to support unkown6 implementation

### ISSUE THREAD

**Issue by vmunich** [rubenvereecken/pokemongo-api#69]
Unkown 6 implementation has just been merged to tejado's API https://github.com/keyphact/pgoapi/pull/6/commits/3ecea0d3207eda41754aaa7ca73cc18d0444e0b9

**Comment by dmadisetti** [comment]
Known. Working on it

**Comment by dmadisetti** [comment]
Would't mind a second pairof eyes:
https://github.com/rubenvereecken/pokemongo-api/pull/70

It works, but not 100% of the time. Super Weird. Will maybe work on it some tomorrow

**Comment by hehachris** [comment]
I am getting the following when running `git submodule sync && git submodule update --init`
```
fatal: reference is not a tree: 873fc50bda9d85b64e2e4032031d4b6282ec95f9
Unable to checkout '873fc50bda9d85b64e2e4032031d4b6282ec95f9' in submodule path 'proto'
```

**Comment by dmadisetti** [comment]
I had to add some Protos. Aeon updated though, so we should be good

**Comment by dmadisetti** [comment]
If anyone can stabilize this, would be much happy. Such wow.

**Comment by dnsBlah** [comment]
What kind of issue's are you facing ?
I'm not getting this reference anywhere :s

**Comment by dmadisetti** [comment]
@dnsBlah is everything working for you? I still come up with blank data sometimes

**Comment by dnsBlah** [comment]
i guess your throttling the server
i made a timestamp check for inventory and one for mapobjects
i have a delay of 5 seconds on inventory and 10 on mapobjects
by using global vars i store the lastchecked timestamp and current one
and alsays making sure that at least those thresholds are in between the timestamps

**Comment by dnsBlah** [comment]
running for 6 hours in a row now
will posts results tomorrow morning :)

**Comment by dmadisetti** [comment]
Wow alright. Haha glad the code works then. I haven't been able to properly test it. It's all been partial guess work

**Comment by dnsBlah** [comment]
crashed out on error 102, reauth, 102, reauth, 102, reauth, 53. crashed.

Implemented your 53 solution now.
Will post results at next crash here. I don't understand the 102.
Just now last crash after 33 minutes
```
[ ] Ran for 33.00 Minute(s)

[ ] Encountered 24 Pokemon(s)
[ ] Captured 12 Pokemon(s)
[ ] Thrown 24 Pokeballs
[ ] Released 12 Pokemon(s)

[ ] Earned 2970 Exp. Points
[ ] Earned 3600 Stardust
[ ] Gathered 29 items
[ ] Dropped 0 items

[ ] Spinned 9 Pokestops
[ ] Traveled 21.08 km's
```
