### ISSUE TITLE
MapObjects lack of pokemon and other issue

### ISSUE THREAD

**Issue by dnsBlah** [rubenvereecken/pokemongo-api#73]
Hi all,

is it just me or are there soo much less pokemons on the map (meaning wild_pokemon and catchable_pokemon)
Is there any way to find more pokemons?
Im already doing a scan in the walkto function, every 10th loop

Besides that, to minimize the mapobject calls I decided to store the results for a while

When I stored the result(s) in a global var, and later on print then out again, i only see 3 empty cells for some reason. Just to be clear, I did not do another request.
When I start the bot, check map objects and stored them globally
Use the global results to filter forts and go there one by one
when arrived I use the same globals to filter pokemons. guess what, its empty?!!

**Comment by jmangeja1** [comment]
Need to increase radius of get map objects call to 1000

**Comment by jmangeja1** [comment]
@dnsblah

**Comment by dnsBlah** [comment]
@jmangeja1 to 1000 !?
Even on 10 I find 196 pokestops, how can that radius be too low for decent pokemons ? 👯 

Any idea about my 're-using' mapobjects issue? Looks like I can't re-use it at all, as it appears empty by then :S

**Comment by jmangeja1** [comment]
@dnsblah I actually haven't used this Ali, but if you look at keyphacts phosphine you'll see they use 1000 as the radius

**Comment by jmangeja1** [comment]
Sorry my spelling is awful. I'm on an iPhone. Ali= API
Phosphine = pygo api

**Comment by dnsBlah** [comment]
hmmm I will have a look in that later then
dont worry, same thing here ;-)

**Comment by dnsBlah** [comment]
I do see a limit of 100 there, going to give it a try :)
With laods of delays I'm already getting more results.

Still an issue when re-using mapobjects like this:
```
aCells = getMapObjects(session)
pokemons = getPokemonsNearby(session, aCells)
for pokemon in pokemons:
    #looping here
pokeForts = getPokeFortsNearby(session,aCells)
#from here aCells is empty! :-/
```

getPokemonsNearby and getPokeFortsNearby look like this:
```
#get pokemons
def getPokemonsNearby(session, cells):
    tPokemons = []
    latitude, longitude, _ = session.getCoordinates()
    for cell in cells.map_cells:
        pokemons = [p for p in cell.wild_pokemons] + [p for p in cell.catchable_pokemons]
        for pokemon in pokemons:
            dist = Location.getDistance(
                latitude,
                longitude,
                pokemon.latitude,
                pokemon.longitude
            )
            tPokemons.append({'distance': dist, 'pokemon': pokemon})

    if len(tPokemons) == 0:
        cells = getMapObjects(session, 10)
        for cell in cells.map_cells:
            pokemons = [p for p in cell.wild_pokemons] + [p for p in cell.catchable_pokemons]
            for pokemon in pokemons:
                dist = Location.getDistance(
                    latitude,
                    longitude,
                    pokemon.latitude,
                    pokemon.longitude
                )
                tPokemons.append({'distance': dist, 'pokemon': pokemon})
            
    tPokemons = sorted(tPokemons, key=lambda k: k['distance'])

    return [instance['pokemon'] for instance in tPokemons]

#get forts (pokestops and gyms)
def getPokeFortsNearby(session, cells):    
    ordered_forts = []
    latitude, longitude, _ = session.getCoordinates()
    for cell in cells.map_cells:
        for fort in cell.forts:
            dist = Location.getDistance(
                latitude,
                longitude,
                fort.latitude,
                fort.longitude
            )
            if fort.type == 1:
                if fort.cooldown_complete_timestamp_ms<time.time():
                    ordered_forts.append({'distance': dist, 'fort': fort})
            else:
                ordered_forts.append({'distance': dist, 'fort': fort})

    ordered_forts = sorted(ordered_forts, key=lambda k: k['distance'])
    
    return [instance['fort'] for instance in ordered_forts]
```

As far as I know, I'm not getting 'new' mapObjects, just trying to re-use the mapobjects i retrieved earlier.
Any idea?

**Comment by jmangeja1** [comment]
@dnsblah. Yea, you can only scan a short distance for Pokemon so not many will show up. I recommend implementing a mapping tool and incorporating that in your program

**Comment by dnsBlah** [comment]
@jmangeja1 Yes I gathered that one :)
I also think there will be a proto update soon related to pokemons nearby, as its back in the game

Anyways yet I don't understand the second part

I retrieve map objects and store it in a variable (aCells)
when I print that variable, I see forts and pokemons
Now I'm using this variable to filter out pokemons and store it in another variable (pokemons)
i loop through them, walk and catch
when finished I use the aCells to filter out the forts
and store it pokeForts
but pokeForts got empty!?

If I print aCells after the pokemon loop
the aCells got empty cells
I haven't rechecked mapobjects yet
Why is it empty?

**Comment by jmangeja1** [comment]
@dnsblah I'm learning N as I go with this app, but what do you mean there has been an update to pokemons nearby in the game? 

Regarding your second question as to why the Acells empty... Are you modifying acells as you loop through Pokemon?

**Comment by jmangeja1** [comment]
@dnsblah let me read your source code posted above.

**Comment by jmangeja1** [comment]
@dnsblah in function getnearbypokemons look at the line cells= getmapobjects(radius =10) that's clearing acells because radius is only 10 and its overwriting acells

**Comment by jmangeja1** [comment]
actually I don't think that should affect it

**Comment by Jefreesujit** [comment]
could someone tell me where to place this libencrypt.so

**Comment by jmangeja1** [comment]
Place it in same directory as the python program that you are running or edit path to include it

**Comment by Jefreesujit** [comment]
still it says no forts found.. what could be the problem?

**Comment by jmangeja1** [comment]
Did you download correct version? I actually don't use this Ali. I use keyphacts edited pgoapi

**Comment by Jefreesujit** [comment]
i just downloaded it.. its the latest one

**Comment by dnsBlah** [comment]
Hi @jmangeja1 ,

thanks for your time, but I only do 
`cells = getMapObjects(session, 10)`
When I don't see any pokemons. Just for the... you know, maybe there are a few in the area where I am at that moment, instead of the area where I scanned aCells
Next to that, it will be stored as 'cells', and not 'aCells' as I pass it to the location :)

**Comment by jmangeja1** [comment]
@dnsblah that line is called when you don't find any Pokemon so it might be clearing out the cells variable. I would test that. Take out that getmapcells call inside the get pokemonsnearby and see if that works. I think that's why your forts are empty

**Comment by dnsBlah** [comment]
@jmangeja1 is it possible by calling getmapobjects to return to a variable named *cells* inside pokemonsnearby function, to overwrite an older variable named *aCells*, which is even outside that function, and without mentioning it to be global at the beginning of pokemonsnearby function?

**Comment by jmangeja1** [comment]
I would google a little but on Python pass by object reference. This is the explanation of how Python passes arguments in functions. From what I can remember a cells should be unaffected once you reassign something in a function. So I'm not sure why you're cells are being cleared out.

**Comment by dnsBlah** [comment]
It's ok for now.. with my workaround with threshold delays
Still, I find it weird that it hardly sees any.
