### ISSUE TITLE
Proper renew API URL ?

### ISSUE THREAD

**Issue by dnsBlah** [rubenvereecken/pokemongo-api#74]
Is it possible to renew the API URL properly ?
On error 53, you get a new API_URL in the response

**Comment by dmadisetti** [comment]
@dnsBlah I put in something that should work. I just can't test since I can't make detailed requests (Even with more sleeps). Care to test out the branch and report back?

https://github.com/rubenvereecken/pokemongo-api/tree/untested

**Comment by dnsBlah** [comment]
Hmmm if it was just that, I might have fixed that :D
Anyway, I just put it in my version and testing it now.
Made some notifications and sounds when the 53 happens :)
Running now

**Comment by dnsBlah** [comment]
How about the 102 (Token renewal) ?
tried to peak into pgoapi etc, but .. it's too different for me

53 occures often after a bunch of 102's.

Waiting for next crash...

**Comment by dnsBlah** [comment]
@dmadisetti 
I finally hitted 53 again.
It sets new URL, but wrong format.
I changed it to
```
self.endpoint = 'https://{0}{1}'.format(
                    res.api_url,
                    '/rpc'
                )
```

Like the original call.
Hopefully will hit it again soon.
Not sure how to hit it manually, any idea?

**Comment by dmadisetti** [comment]
Hummm. We'll have to explore token refresh separately, but newest merge should also fix some of this

**Comment by dnsBlah** [comment]
Nice cleanup! Thanks :)
