### ISSUE TITLE
getProfile doesn't include all data from protos

### ISSUE THREAD

**Issue by earshel** [rubenvereecken/pokemongo-api#75]
First off, thank you very much for the API. I am using it in one of my projects and it's fantastic. I've come to a point in my project where I'd like to query the server for player stats and I've hit a roadblock. I've looked at the protos and it seems like the PlayerData_Pb2 does not contain the /data/player/playerstats_pb2 proto, and I am not familiar enough with ProtoBuf to fix it. I'm hoping that you might be able to offer some insight. Thanks again!

**Comment by dnsBlah** [comment]
because its in inventory, for some reason ;-)

**Comment by dmadisetti** [comment]
The player stats come in the inventory request, so it's just slapped on to the Inventory object

**Comment by earshel** [comment]
Ah, who'd have guessed. Thanks for the prompt reply!
