### ISSUE TITLE
Error when I try to getMapObjects with radius >50

### ISSUE THREAD

**Issue by enayfuos** [rubenvereecken/pokemongo-api#77]
Hey,
When i run the script with a radius<50 I get 0 pokémon...:

> Line 40,demo.py - 2016-08-08 23:05:31,875 - INFO - Finding Nearby Pokemon:
Line 46,demo.py - 2016-08-08 23:05:32,174 - INFO - Current pos: 48.579415, 7.740
778
Line 195,demo.py - 2016-08-08 23:05:32,174 - INFO - Finding Nearest Fort:
Line 173,demo.py - 2016-08-08 23:05:32,176 - INFO - Sorting Nearest Forts:
Line 199,demo.py - 2016-08-08 23:05:32,480 - INFO - No forts found..

But when I put a radius >50, I get this error:

> Line 40,demo.py - 2016-08-08 23:11:56,565 - INFO - Finding Nearby Pokemon:
> Line 224,session_bare.py - 2016-08-08 23:11:56,694 - ERROR - status_code: 3
> request_id: 117650377702
> unknown6 {
>   response_type: 6
>   unknown2 {
>     unknown1: 1
>   }
> }
> returns: ""
> 
> Traceback (most recent call last):
>   File "pogo\demo.py", line 408, in <
> module>
>     pokemon = findBestPokemon(session)
>   File "pogo\demo.py", line 41, in fi
> ndBestPokemon
>     cells = session.getMapObjects()
>   File "pogo\session.py", line 100, i
> n getMapObjects
>     res = self.wrapAndRequest(payload)
>   File "pogo\session_bare.py", line 1
> 83, in wrapAndRequest
>     self.parseDefault(res)
>   File "pogo\session_bare.py", line 2
> 25, in parseDefault
>     raise PogoResponseException("Expected response not returned")
> custom_exceptions.PogoResponseException: Expected response not returned

Anyone knows why it occures?

**Comment by dmadisetti** [comment]
Not able to replicate? Going to guess it does't have to do with radius

**Comment by enayfuos** [comment]
Yes, it's more about the response that i get when looking for nearest pokemons.
Inside the parseDefault(), the length of res.returns is 1: ['']

I don't know if it's about the encryption. Cause I didn't use the encrypt.dll..

**Comment by dnsBlah** [comment]
using the .so its doing fine.
I'm guessing its a matter of throttling the server with your requests

**Comment by ciol06** [comment]
Same thing for me: radius = 49 is ok but with 50 i get this error, related to unknown 6 (!!!):

Line 40,demo.py - 2016-08-09 10:22:35,477 - INFO - Finding Nearby Pokemon:
Line 224,session_bare.py - 2016-08-09 10:22:35,646 - ERROR - status_code: 3
request_id: 528144263001
unknown6 {
  response_type: 6
  unknown2 {
    unknown1: 1
  }
}
returns: ""

Traceback (most recent call last):
  File "demo.py", line 410, in <module>
    pokemon = findBestPokemon(session)
  File "demo.py", line 41, in findBestPokemon
    cells = session.getMapObjects()
  File "/media/sf_Dropbox/python/pokemon_go/pokemongo-api-master/pogo/session.py", line 100, in getMapObjects
    res = self.wrapAndRequest(payload)
  File "/media/sf_Dropbox/python/pokemon_go/pokemongo-api-master/pogo/session_bare.py", line 183, in wrapAndRequest
    self.parseDefault(res)
  File "/media/sf_Dropbox/python/pokemon_go/pokemongo-api-master/pogo/session_bare.py", line 225, in parseDefault
    raise PogoResponseException("Expected response not returned")
custom_exceptions.PogoResponseException: Expected response not returned

Other strange thing: with radius=40, I didnt find any pokemon, trying many locations/times...

**Comment by enayfuos** [comment]
@dnsBlah I'll try to put the sleep. 

I'm using the .dll cause i'm under windows, but I will test this on Linux with the .so.

Thanks for help.

**Comment by dnsBlah** [comment]
Why using such a big radius anyways ?
I'm using 10 and it finds up to like... 196 forts, ok.. im wondering around in Tokyo.. but still
10 is a pretty big radius

**Comment by enayfuos** [comment]
When I use less than 50 I didn't get any pokémon... even if there are many around me. It's the same thing with @ciol06... 

@ciol06 Did you use the encryption file? Where did you put it?

**Comment by dnsBlah** [comment]
@enayfuos For me it's quite random. With radius like... 10 I can see around.. 120 pokestops, in public crowded and attractive area.
The same area with radius 50, sees nothing
with 49 it does, like @ciol06 mentioned

However! This might be complete random, as I have the same issue with 10 once a while.
Thankfully I'm not exiting my script when it doesn't find anything, but keeps looping.

Eventually it just finds the pokemons and stops near, and starts playing.

This might take up like... 15 times? 15 * 10 seconds + 15 * +/- 3 seconds ( a few minutes )

**Comment by enayfuos** [comment]
@dnsBlah You have the chance to have the possibilitie to see pokestops and pokemons. Our problem is that we can't see anything :D => 0 pokémons and 0 pokéstops even if I'm near of 5 pokestops...

**Comment by dnsBlah** [comment]
Thats exactly an issue, ain't it ;-D
Again, I find it complete random.

Please do a loop around it for like ... i dont know, test it with 30 times in a row  ?
It might be possible that it suddenly does see objects.

Just now after 15 loops I did receive objects back..

**Comment by enayfuos** [comment]
Yes that could be... :D I'll do a loop until I get something.

**Comment by dnsBlah** [comment]
Just let us know, I'm still fiddling around with the threshold/cooldown and radius
radius 25, gives me 600+ pokestops ;-D

So again, I don't see why you need 50 :D

**Comment by enayfuos** [comment]
I tried 50 cause I got nothing with less, I was adding 10 to radius each time and when arrived to 50 it crashed.. I'll try with 20 and loop in few hours..

**Comment by dnsBlah** [comment]
-_- I'm just keeping focussed on a big area.
I downscaled my radius to 9 now.
And finding pokestops within a distance of +/- 1000m
Find below.

p.s. these are not ordered yet.

```
Distance: 734.115960511
Distance: 848.090962235
Distance: 769.970842082
Distance: 694.374693178
Distance: 811.158314695
Distance: 738.413676273
Distance: 729.352555298
Distance: 834.352663086
Distance: 782.647364852
Distance: 729.098247198
Distance: 831.217445636
Distance: 743.813853767
Distance: 600.893135802
Distance: 528.703605576
Distance: 703.127864351
Distance: 850.630987822
Distance: 765.583401197
Distance: 829.606001772
Distance: 789.601814068
Distance: 844.115731665
Distance: 874.325162407
Distance: 759.462096787
Distance: 838.215258889
Distance: 801.273486392
Distance: 871.272884749
Distance: 843.370980302
Distance: 735.590536123
Distance: 827.701633349
Distance: 956.676753594
Distance: 773.425172033
Distance: 784.901342149
Distance: 939.044808018
Distance: 1010.25937804
Distance: 910.894831329
Distance: 786.938067574
Distance: 862.510489623
Distance: 554.99810995
Distance: 481.054749515
Distance: 606.910703861
Distance: 677.041043028
Distance: 617.281123896
Distance: 656.588084795
Distance: 246.468901036
Distance: 281.00521219
Distance: 355.005216179
Distance: 221.817257483
Distance: 244.037632671
Distance: 436.578406541
Distance: 342.779726357
Distance: 443.030172646
Distance: 263.068504437
Distance: 328.599430142
Distance: 409.414175041
Distance: 422.370597748
Distance: 408.795425883
Distance: 300.055400794
Distance: 374.392062632
Distance: 200.148465321
Distance: 49.1946706788
Distance: 161.838787298
Distance: 78.8699820158
Distance: 129.859343987
Distance: 146.763513653
Distance: 150.783108706
Distance: 66.204250624
Distance: 235.565738922
Distance: 39.9574815438
Distance: 177.835022726
Distance: 218.813696273
Distance: 262.775145207
Distance: 304.847675713
Distance: 318.407737107
Distance: 176.98759114
Distance: 322.574402885
Distance: 305.26710079
Distance: 236.98462275
Distance: 379.07294268
Distance: 380.724169702
Distance: 434.102965617
Distance: 631.106142542
Distance: 530.24416508
Distance: 637.410690979
Distance: 562.593943229
Distance: 425.087767768
Distance: 453.117883938
Distance: 565.204720468
Distance: 516.712324975
Distance: 607.825043644
Distance: 531.46033317
Distance: 592.378982738
Distance: 498.080285555
Distance: 571.406700055
Distance: 597.596254759
Distance: 573.914754447
Distance: 625.592794425
Distance: 827.844700385
Distance: 786.046944104
Distance: 760.051332804
Distance: 820.687756657
Distance: 704.209248304
Distance: 666.900556762
Distance: 762.265647881
Distance: 815.770283249
Distance: 692.60669853
Distance: 711.562388245
Distance: 924.508473959
Distance: 659.411907537
Distance: 634.606321449
Distance: 780.723808809
Distance: 703.979620459
Distance: 780.552940651
Distance: 840.493744337
Distance: 736.645232934
Distance: 773.449758957
Distance: 832.236906058
Distance: 972.478321669
Distance: 1168.70020746
Distance: 1102.92984101
Distance: 866.159622241
Distance: 1003.37397657
Distance: 1026.46507054
Distance: 928.871846433
Distance: 873.264753316
Distance: 927.557672926
Distance: 1004.64634574
Distance: 930.981777109
Distance: 1083.86726949
Distance: 1222.33087703
Distance: 1188.86768573
Distance: 1282.43940272
Distance: 1153.33685764
Distance: 1323.92251239
Distance: 1392.00354564
Distance: 1324.24976074
Distance: 1230.91520135
Distance: 1310.75233443
Distance: 1134.67734134
Distance: 1215.76924953
Distance: 1114.40494362
Distance: 1145.1333598
Distance: 1090.0441928
Distance: 1169.21664256
Distance: 1078.87228942
Distance: 1156.57212314
Distance: 1278.2117445
Distance: 1193.80265229
Distance: 1187.17796361
Distance: 1112.57792006
Distance: 1294.21112391
Distance: 893.559369143
Distance: 969.014675196
Distance: 1077.14344346
Distance: 986.105520933
Distance: 1059.67647484
Distance: 874.465012859
Distance: 951.38685095
Distance: 869.000597143
Distance: 834.297122392
Distance: 1062.28027069
```

**Comment by dnsBlah** [comment]
@enayfuos Any results when looping and sleeping?

**Comment by enayfuos** [comment]
@dnsBlah I'll test it now.

**Comment by enayfuos** [comment]
@dnsBlah I looped with a sleep(5) each time before searching pokemons. 
Returned values that I appends are:
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None] :/

**Comment by enayfuos** [comment]
@dnsBlah it's fixed, it was a problem with the library, I recompile it and now it works.. Thanks for help.
