### ISSUE TITLE
Running demo.py shows 'no forts found'

### ISSUE THREAD

**Issue by Jefreesujit** [rubenvereecken/pokemongo-api#79]
I pulled out the latest code, updated the requirements and added libencrypt.so in the repo directory. When i try to run demo.py it executes fine, but says 'no forts found' and stops.

**Comment by Jefreesujit** [comment]
i tried to log, the cells.mapcells, and found it has no forts array in the cell object.. could someone help me out here..

**Comment by dnsBlah** [comment]
Do you have the encryption file ?

**Comment by Jefreesujit** [comment]
yeah this one ryt.. libencrypt.so ? i placed in pogo directory where demo.py is present.. where should i place it?

**Comment by dnsBlah** [comment]
Yes in the same directory where you are calling the demo.py
Then when you call the script:
./demo.py -a PTC -u USERNAME -p PASSWORD -e "libencrypt.so"

**Comment by Jefreesujit** [comment]
i tried that out, but still it shows no forts found.. basically the cells object has only the cell id and timestamp.

**Comment by dnsBlah** [comment]
put time.sleep(10) before the getmapobjects function

**Comment by Jefreesujit** [comment]
Dude, even that didnt work out.. i appreciate that you take time to help me out.. but i dont know whats going wrong.. i m not able to figure it out

**Comment by dnsBlah** [comment]
What OS are you running? For Windows I think you have a better chance using the .dll file

**Comment by Jefreesujit** [comment]
i m using mac osx el captian

**Comment by dnsBlah** [comment]
Actually, I see now, I dropped both, the .so and .dll in the same folder.
[http://www.filedropper.com/archive_34](http://www.filedropper.com/archive_34)
Download that, thats what I'm using.

And to make my life easier, I just changed the argument for the file:
```
poko_session = PokeAuthSession(
        args.username,
        args.password,
        args.auth,
        args.encrypt_lib,
        geo_key=args.geo_key
)
```

to

```
poko_session = PokeAuthSession(
        args.username,
        args.password,
        args.auth,
        "encrypt.so",
        geo_key=args.geo_key
)
```

**Comment by Jefreesujit** [comment]
Still it doesnt work.. i m getting frustrated, i dont think this is gonna work out.. Thanks for your help..

**Comment by dnsBlah** [comment]
hm.. strange tho.. I'm sorry, I can't help out more either then. Maybe someone else on here can tho.
Be patient.

**Comment by joeljacobson** [comment]
I'm also having demo issues, have both libencrypt.so and encrypt.dll in the pogo directory  with the demo.py. Inventory gets printed and then errors with:

```Line 40,demo.py - 2016-08-09 22:03:49,350 - INFO - Finding Nearby Pokemon:
Line 224,session_bare.py - 2016-08-09 22:03:49,400 - ERROR - status_code: 52```

**Comment by dmadisetti** [comment]
Error 52 mean you've been rate limited

**Comment by joeljacobson** [comment]
Thanks for the reply, is that them imposing some kind of soft ban? or is that a permanent thing? 

What recommendation would you have? Anything I can do or just create a new account? 

Thanks in advance for your help.

**Comment by dmadisetti** [comment]
Just put in higher sleeps between requests. Demo is just an example of how you might use the API, not meant to be 100%. However, I've been having having issues too. I'll debug some more

**Comment by joeljacobson** [comment]
Will do, thank you.

**Comment by dmadisetti** [comment]
Cool. Also, newest branch has better error handling. About to merge into master

**Comment by Jefreesujit** [comment]
hey dmadisetti, this issue has not been resolved for me, why ave you closed this issue?

**Comment by dnsBlah** [comment]
Jefree, did you try more bots ?
Do you have the possibility to try using a VPN or proxy ?

I've experienced an ban on the WAN side. And it really has to do with throttling the server(s)

**Comment by Jefreesujit** [comment]
Try more bots, in the sense? execute more no of times? even in that case i m not able to find any pokemons or forts in my newly created trainer account too.

**Comment by Jefreesujit** [comment]
where will i be getting encrypt.dll if have to try it out on windows?

**Comment by davjimvar** [comment]
@dnsBlah uploaded at this [http://www.filedropper.com/archive_34](url) but to me this file doesn't work

**Comment by Jefreesujit** [comment]
yeah, even for me.. it wasnt working..

**Comment by dnsBlah** [comment]
I'n using that .so file
Running on El Capitan

**Comment by davjimvar** [comment]
but in windows not is valid .so

**Comment by dnsBlah** [comment]
@Jefreesujit
please try these commands and try the demo again

cp encrypt.dll /usr/local/lib/encrypt.dll
export LD_LIBRARY_PATH=/usr/local/lib

**Comment by Jefreesujit** [comment]
i executed these commands, and should i include -e "encrypt.dll" along with my command?

**Comment by dnsBlah** [comment]
put the .so in the command
