### ISSUE TITLE
getMapObjects default radius too high

### ISSUE THREAD

**Issue by dnsBlah** [rubenvereecken/pokemongo-api#81]
The getMapObject Radius is now set to 1000 by default.
With  such high radius I get:
`{'responses': {'ENCOUNTER': {'status': 6}}, 'request_id': 123167996238794584, 'status_code': 1, 'unknown6': [{'unknown2': {'unknown1': 1}, 'response_type': 6}]}`

**Comment by dmadisetti** [comment]
Changed back to 10
