### ISSUE TITLE
Download encrypt.dll

### ISSUE THREAD

**Issue by davjimvar** [rubenvereecken/pokemongo-api#85]
I downloaded this file [https://github.com/rubenvereecken/pokemongo-api/issues/79#issuecomment-238664694](url) but not work in windows, throw this:

> OSError: [WinError 193] %1 no es una aplicación Win32 válida

Where I can donwload this file??
Thank!

**Comment by dnsBlah** [comment]
Thats because its a unix compiled version..

**Comment by davjimvar** [comment]
but the .dll version should work in windows or not?

**Comment by dnsBlah** [comment]
no its for unix

**Comment by dnsBlah** [comment]
try this one
https://www.sendspace.com/file/bq0hcn

**Comment by dnsBlah** [comment]
p.s I did not upload this one so can't really tell if its correct,working or safe to use

**Comment by enayfuos** [comment]
Maybe you download a 64bits encrypt.dll you'll need a 32bits

**Comment by davjimvar** [comment]
@dnsBlah with this file, I think that work but now, throw this:

> Traceback (most recent call last):
>   File "C:/Users/Error/git/pokemongo-api/pogo/bot.py", line 464, in <module>
>     pokemon = findBestPokemon(session)
>   File "C:/Users/Error/git/pokemongo-api/pogo/bot.py", line 41, in findBestPokemon
>     cells = session.getMapObjects()
>   File "C:\Users\Error\git\pokemongo-api\pogo\session.py", line 87, in getMapObjects
>     res = self.wrapAndRequest(payload)
>   File "C:\Users\Error\git\pokemongo-api\pogo\session_bare.py", line 186, in wrapAndRequest
>     res = self.request(self.wrapInRequest(payload, defaults=defaults))
>   File "C:\Users\Error\git\pokemongo-api\pogo\session_bare.py", line 135, in wrapInRequest
>     signature = hashSignature(proto, self._encryptLib)
>   File "C:\Users\Error\git\pokemongo-api\pogo\util.py", line 102, in hashSignature
>     return b''.join(map(chr, output))
> TypeError: sequence item 0: expected a bytes-like object, str found

any idea?

**Comment by dnsBlah** [comment]
oi thats weird
please check pip freeze
and compare it with requirements.txt

**Comment by davjimvar** [comment]
are identical. I am using python 3.5 but in python 2.7 I can not install PyCryptodome

**Comment by dnsBlah** [comment]
hmm im using 2.7
and xxhash is pretty much crucial i guess

**Comment by davjimvar** [comment]
finally, all work!!! Now, I use python 2.7 with al requirements. For xxhash and pycryptodomex I searched .whl version but now, work all correctly.

Thanks for all!! And I will try to create some interesting method for all!
