### ISSUE TITLE
findBestPokemon() function not working ?

### ISSUE THREAD

**Issue by vnea** [rubenvereecken/pokemongo-api#92]
I tried the new version for an hour and it seems like findBestPokemon() function does not work anymore.
Do you have the same problem ?

**Comment by dnsBlah** [comment]
Please elaborate your issue.
Why do you think it doesn't work anymore ?

**Comment by vnea** [comment]
As I said, I ran the bot (simpleBot function) for an hour and the bot didn't found any Pokemon.
I have an old version of the project on my computer and I don't have this problem.

**Comment by joeljacobson** [comment]
It works for me.

**Comment by dnsBlah** [comment]
everything works for me tho
however I only find 1...3 pokemons a time

**Comment by vnea** [comment]
Well nvm, I'll keep using the old version, thank you ! :)
